/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zegar;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author Paweł Kuźmicki
 */
public class ChoiceDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChoiceDialog
     */
    public ChoiceDialog(java.awt.Frame parent, boolean modal, EventsDataBase database, String day,
            MyCalendar myCalendar) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.selectedDay = day;
        this.myCalendar = myCalendar;
        
        GregorianCalendar date = new GregorianCalendar();
        int month = date.get(Calendar.MONTH) + 1;
        this.setTitle( this.selectedDay + "." + month + "." + date.get(Calendar.YEAR));
        
        
        this.database = database;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        first = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newPanel = new javax.swing.JPanel();
        buttonsPanel1 = new javax.swing.JPanel();
        saveNewButton = new javax.swing.JButton();
        cancelNewButton = new javax.swing.JButton();
        centerNewPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        hourTextFiels = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        showPanel = new javax.swing.JPanel();
        buttonsPanel2 = new javax.swing.JPanel();
        backShowButton = new javax.swing.JButton();
        editShowPanel = new javax.swing.JButton();
        eventsListShowPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventsList = new javax.swing.JList<>();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(335, 245));
        mainPanel.setLayout(new java.awt.CardLayout());

        first.setBackground(new java.awt.Color(51, 255, 0));
        first.setName("firstPanel"); // NOI18N
        first.setPreferredSize(new java.awt.Dimension(335, 245));
        first.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setBackground(new java.awt.Color(51, 255, 0));
        buttonsPanel.setLayout(new java.awt.GridLayout(2, 2));

        newButton.setText("new event");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(newButton);

        editButton.setText("edit event");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(editButton);

        showButton.setText("show event");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(showButton);

        deleteButton.setText("delete event");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(deleteButton);

        first.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        jLabel2.setBackground(new java.awt.Color(51, 255, 0));
        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 0, 50)); // NOI18N
        jLabel2.setText("What do U want?");
        first.add(jLabel2, java.awt.BorderLayout.CENTER);

        mainPanel.add(first, "first");

        newPanel.setBackground(new java.awt.Color(51, 255, 0));
        newPanel.setName("newPanel"); // NOI18N
        newPanel.setPreferredSize(new java.awt.Dimension(335, 245));
        newPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel1.setBackground(new java.awt.Color(51, 255, 0));
        buttonsPanel1.setLayout(new java.awt.GridLayout(1, 2));

        saveNewButton.setText("save event");
        saveNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewButtonActionPerformed(evt);
            }
        });
        buttonsPanel1.add(saveNewButton);

        cancelNewButton.setText("cancel");
        cancelNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewButtonActionPerformed(evt);
            }
        });
        buttonsPanel1.add(cancelNewButton);

        newPanel.add(buttonsPanel1, java.awt.BorderLayout.SOUTH);

        centerNewPanel.setBackground(new java.awt.Color(51, 255, 0));

        jLabel1.setText("Name:");

        jLabel4.setText("Hour:");

        jLabel5.setText("Description:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout centerNewPanelLayout = new javax.swing.GroupLayout(centerNewPanel);
        centerNewPanel.setLayout(centerNewPanelLayout);
        centerNewPanelLayout.setHorizontalGroup(
            centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerNewPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hourTextFiels, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        centerNewPanelLayout.setVerticalGroup(
            centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerNewPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hourTextFiels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newPanel.add(centerNewPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(newPanel, "newPanel");

        showPanel.setBackground(new java.awt.Color(51, 255, 0));
        showPanel.setName("newPanel"); // NOI18N
        showPanel.setPreferredSize(new java.awt.Dimension(335, 245));
        showPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel2.setBackground(new java.awt.Color(51, 255, 0));
        buttonsPanel2.setLayout(new java.awt.GridLayout(1, 2));

        backShowButton.setText("back");
        backShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backShowButtonActionPerformed(evt);
            }
        });
        buttonsPanel2.add(backShowButton);

        editShowPanel.setText("edit events");
        editShowPanel.setEnabled(false);
        editShowPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editShowPanelActionPerformed(evt);
            }
        });
        buttonsPanel2.add(editShowPanel);

        showPanel.add(buttonsPanel2, java.awt.BorderLayout.SOUTH);

        eventsListShowPanel.setBackground(new java.awt.Color(51, 255, 0));

        eventsList.setBackground(new java.awt.Color(66, 222, 0));
        eventsList.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        eventsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventsList.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jScrollPane2.setViewportView(eventsList);

        javax.swing.GroupLayout eventsListShowPanelLayout = new javax.swing.GroupLayout(eventsListShowPanel);
        eventsListShowPanel.setLayout(eventsListShowPanelLayout);
        eventsListShowPanelLayout.setHorizontalGroup(
            eventsListShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(eventsListShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(eventsListShowPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        eventsListShowPanelLayout.setVerticalGroup(
            eventsListShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
            .addGroup(eventsListShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventsListShowPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        showPanel.add(eventsListShowPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(showPanel, "showPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        
        card.show(mainPanel, "newPanel");
        System.out.println("newButton clicked");
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewButtonActionPerformed
        
        Event event = new Event( nameTextField.getText(), this.selectedDay, hourTextFiels.getText(), descriptionTextArea.getText()); 
        database.insert(event);
        
        myCalendar.setDaysWithEvent(database.daysWithEvent());
        
        CardLayout card = (CardLayout) mainPanel.getLayout();
        
        card.show(mainPanel, "first");
        
        
        System.out.println("saveButton clicked");
    }//GEN-LAST:event_saveNewButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        database.deleteEventsIn(selectedDay);
        myCalendar.setDaysWithEvent(database.daysWithEvent());
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewButtonActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "first");
       // card.next(mainPanel);
    }//GEN-LAST:event_cancelNewButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
         
        ArrayList<Event> events = database.getEventsIn(this.selectedDay);
        
        if(events.size() == 0 ){
            System.err.println("Pusta baza eventów tego dnia");
        }
        
        String[] tab = new String[15];
        for(int i = 0; i < events.size(); i++){
            
            tab[i] = events.get(i).toString(); // hiding event ordinal number
        }
    
        eventsList.setListData(tab);  //2 clicks in "showbutton" destroy eventsList
        
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "showPanel");
        
    }//GEN-LAST:event_showButtonActionPerformed

    private void backShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backShowButtonActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "first");
        
        eventsListShowPanel.removeAll();
    }//GEN-LAST:event_backShowButtonActionPerformed

    private void editShowPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editShowPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editShowPanelActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backShowButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel buttonsPanel1;
    private javax.swing.JPanel buttonsPanel2;
    private javax.swing.JButton cancelNewButton;
    private javax.swing.JPanel centerNewPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editShowPanel;
    private javax.swing.JList<String> eventsList;
    private javax.swing.JPanel eventsListShowPanel;
    private javax.swing.JPanel first;
    private javax.swing.JTextField hourTextFiels;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton newButton;
    private javax.swing.JPanel newPanel;
    private javax.swing.JButton saveNewButton;
    private javax.swing.JButton showButton;
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
    private String selectedDay;
    private EventsDataBase database;
    private MyCalendar myCalendar;
    
}
